// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrestamosBancarios.Data;

#nullable disable

namespace PrestamosBancarios.Migrations
{
    [DbContext(typeof(PrestamoDbContext))]
    [Migration("20250221200419_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("PrestamosBancarios.Models.Prestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdAdministrador")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoRechazo")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlazoEnMeses")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Prestamos");
                });
#pragma warning restore 612, 618
        }
    }
}
